// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cache_data.sql

package repo

import (
	"context"
)

const createCacheData = `-- name: CreateCacheData :one
INSERT INTO cache_data (technology, cache_type, core_data, custom_fields, schema_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, technology, cache_type, core_data, custom_fields, schema_version, created_at, updated_at
`

type CreateCacheDataParams struct {
	Technology    string `json:"technology"`
	CacheType     string `json:"cache_type"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) CreateCacheData(ctx context.Context, arg CreateCacheDataParams) (CacheDatum, error) {
	row := q.db.QueryRow(ctx, createCacheData,
		arg.Technology,
		arg.CacheType,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i CacheDatum
	err := row.Scan(
		&i.ID,
		&i.Technology,
		&i.CacheType,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCacheData = `-- name: DeleteCacheData :exec
DELETE FROM cache_data
WHERE id = $1
`

func (q *Queries) DeleteCacheData(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCacheData, id)
	return err
}

const getCacheData = `-- name: GetCacheData :one
SELECT id, technology, cache_type, core_data, custom_fields, schema_version, created_at, updated_at FROM cache_data
WHERE id = $1
`

func (q *Queries) GetCacheData(ctx context.Context, id string) (CacheDatum, error) {
	row := q.db.QueryRow(ctx, getCacheData, id)
	var i CacheDatum
	err := row.Scan(
		&i.ID,
		&i.Technology,
		&i.CacheType,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCacheData = `-- name: ListCacheData :many
SELECT id, technology, cache_type, core_data, custom_fields, schema_version, created_at, updated_at FROM cache_data
ORDER BY created_at DESC
`

func (q *Queries) ListCacheData(ctx context.Context) ([]CacheDatum, error) {
	rows, err := q.db.Query(ctx, listCacheData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CacheDatum{}
	for rows.Next() {
		var i CacheDatum
		if err := rows.Scan(
			&i.ID,
			&i.Technology,
			&i.CacheType,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCacheDataByTechnology = `-- name: ListCacheDataByTechnology :many
SELECT id, technology, cache_type, core_data, custom_fields, schema_version, created_at, updated_at FROM cache_data
WHERE technology = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCacheDataByTechnology(ctx context.Context, technology string) ([]CacheDatum, error) {
	rows, err := q.db.Query(ctx, listCacheDataByTechnology, technology)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CacheDatum{}
	for rows.Next() {
		var i CacheDatum
		if err := rows.Scan(
			&i.ID,
			&i.Technology,
			&i.CacheType,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCacheDataByField = `-- name: SearchCacheDataByField :many
SELECT id, technology, cache_type, core_data, custom_fields, schema_version, created_at, updated_at FROM cache_data
WHERE core_data @> $1 OR custom_fields @> $1
ORDER BY created_at DESC
`

func (q *Queries) SearchCacheDataByField(ctx context.Context, coreData []byte) ([]CacheDatum, error) {
	rows, err := q.db.Query(ctx, searchCacheDataByField, coreData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CacheDatum{}
	for rows.Next() {
		var i CacheDatum
		if err := rows.Scan(
			&i.ID,
			&i.Technology,
			&i.CacheType,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCacheData = `-- name: UpdateCacheData :one
UPDATE cache_data 
SET technology = $2, cache_type = $3, core_data = $4, custom_fields = $5, 
    schema_version = $6, updated_at = now()
WHERE id = $1
RETURNING id, technology, cache_type, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdateCacheDataParams struct {
	ID            string `json:"id"`
	Technology    string `json:"technology"`
	CacheType     string `json:"cache_type"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) UpdateCacheData(ctx context.Context, arg UpdateCacheDataParams) (CacheDatum, error) {
	row := q.db.QueryRow(ctx, updateCacheData,
		arg.ID,
		arg.Technology,
		arg.CacheType,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i CacheDatum
	err := row.Scan(
		&i.ID,
		&i.Technology,
		&i.CacheType,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
