// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: docker_container.sql

package repo

import (
	"context"
)

const addCustomFieldToDockerContainer = `-- name: AddCustomFieldToDockerContainer :one
UPDATE docker_container 
SET custom_fields = jsonb_set(custom_fields, $2, $3), updated_at = now()
WHERE id = $1
RETURNING id, name, status, core_data, custom_fields, schema_version, created_at, updated_at
`

type AddCustomFieldToDockerContainerParams struct {
	ID          string      `json:"id"`
	Path        interface{} `json:"path"`
	Replacement []byte      `json:"replacement"`
}

func (q *Queries) AddCustomFieldToDockerContainer(ctx context.Context, arg AddCustomFieldToDockerContainerParams) (DockerContainer, error) {
	row := q.db.QueryRow(ctx, addCustomFieldToDockerContainer, arg.ID, arg.Path, arg.Replacement)
	var i DockerContainer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDockerContainer = `-- name: CreateDockerContainer :one
INSERT INTO docker_container (name, status, core_data, custom_fields, schema_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, status, core_data, custom_fields, schema_version, created_at, updated_at
`

type CreateDockerContainerParams struct {
	Name          string `json:"name"`
	Status        string `json:"status"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) CreateDockerContainer(ctx context.Context, arg CreateDockerContainerParams) (DockerContainer, error) {
	row := q.db.QueryRow(ctx, createDockerContainer,
		arg.Name,
		arg.Status,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i DockerContainer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDockerContainer = `-- name: DeleteDockerContainer :exec
DELETE FROM docker_container
WHERE id = $1
`

func (q *Queries) DeleteDockerContainer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDockerContainer, id)
	return err
}

const getDockerContainer = `-- name: GetDockerContainer :one
SELECT id, name, status, core_data, custom_fields, schema_version, created_at, updated_at FROM docker_container
WHERE id = $1
`

func (q *Queries) GetDockerContainer(ctx context.Context, id string) (DockerContainer, error) {
	row := q.db.QueryRow(ctx, getDockerContainer, id)
	var i DockerContainer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDockerContainers = `-- name: ListDockerContainers :many
SELECT id, name, status, core_data, custom_fields, schema_version, created_at, updated_at FROM docker_container
ORDER BY created_at DESC
`

func (q *Queries) ListDockerContainers(ctx context.Context) ([]DockerContainer, error) {
	rows, err := q.db.Query(ctx, listDockerContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DockerContainer{}
	for rows.Next() {
		var i DockerContainer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFieldFromDockerContainer = `-- name: RemoveFieldFromDockerContainer :one
UPDATE docker_container 
SET core_data = core_data - $2, custom_fields = custom_fields - $2, updated_at = now()
WHERE id = $1
RETURNING id, name, status, core_data, custom_fields, schema_version, created_at, updated_at
`

type RemoveFieldFromDockerContainerParams struct {
	ID       string `json:"id"`
	CoreData []byte `json:"core_data"`
}

func (q *Queries) RemoveFieldFromDockerContainer(ctx context.Context, arg RemoveFieldFromDockerContainerParams) (DockerContainer, error) {
	row := q.db.QueryRow(ctx, removeFieldFromDockerContainer, arg.ID, arg.CoreData)
	var i DockerContainer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchDockerContainersByField = `-- name: SearchDockerContainersByField :many
SELECT id, name, status, core_data, custom_fields, schema_version, created_at, updated_at FROM docker_container
WHERE core_data @> $1 OR custom_fields @> $1
ORDER BY created_at DESC
`

func (q *Queries) SearchDockerContainersByField(ctx context.Context, coreData []byte) ([]DockerContainer, error) {
	rows, err := q.db.Query(ctx, searchDockerContainersByField, coreData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DockerContainer{}
	for rows.Next() {
		var i DockerContainer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDockerContainer = `-- name: UpdateDockerContainer :one
UPDATE docker_container 
SET name = $2, status = $3, core_data = $4, custom_fields = $5, 
    schema_version = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, status, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdateDockerContainerParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Status        string `json:"status"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) UpdateDockerContainer(ctx context.Context, arg UpdateDockerContainerParams) (DockerContainer, error) {
	row := q.db.QueryRow(ctx, updateDockerContainer,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i DockerContainer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDockerContainerField = `-- name: UpdateDockerContainerField :one
UPDATE docker_container 
SET core_data = jsonb_set(core_data, $2, $3), updated_at = now()
WHERE id = $1
RETURNING id, name, status, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdateDockerContainerFieldParams struct {
	ID          string      `json:"id"`
	Path        interface{} `json:"path"`
	Replacement []byte      `json:"replacement"`
}

func (q *Queries) UpdateDockerContainerField(ctx context.Context, arg UpdateDockerContainerFieldParams) (DockerContainer, error) {
	row := q.db.QueryRow(ctx, updateDockerContainerField, arg.ID, arg.Path, arg.Replacement)
	var i DockerContainer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
