// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: editor_config.sql

package repo

import (
	"context"
)

const createEditorConfig = `-- name: CreateEditorConfig :one
INSERT INTO editor_config (name, config_data)
VALUES ($1, $2)
RETURNING id, name, config_data, created_at, updated_at
`

type CreateEditorConfigParams struct {
	Name       string `json:"name"`
	ConfigData []byte `json:"config_data"`
}

func (q *Queries) CreateEditorConfig(ctx context.Context, arg CreateEditorConfigParams) (EditorConfig, error) {
	row := q.db.QueryRow(ctx, createEditorConfig, arg.Name, arg.ConfigData)
	var i EditorConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEditorConfig = `-- name: DeleteEditorConfig :exec
DELETE FROM editor_config
WHERE id = $1
`

func (q *Queries) DeleteEditorConfig(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEditorConfig, id)
	return err
}

const getEditorConfig = `-- name: GetEditorConfig :one
SELECT id, name, config_data, created_at, updated_at FROM editor_config
WHERE id = $1
`

func (q *Queries) GetEditorConfig(ctx context.Context, id string) (EditorConfig, error) {
	row := q.db.QueryRow(ctx, getEditorConfig, id)
	var i EditorConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEditorConfigs = `-- name: ListEditorConfigs :many
SELECT id, name, config_data, created_at, updated_at FROM editor_config
ORDER BY created_at DESC
`

func (q *Queries) ListEditorConfigs(ctx context.Context) ([]EditorConfig, error) {
	rows, err := q.db.Query(ctx, listEditorConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EditorConfig{}
	for rows.Next() {
		var i EditorConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ConfigData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEditorConfig = `-- name: UpdateEditorConfig :one
UPDATE editor_config 
SET name = $2, config_data = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, config_data, created_at, updated_at
`

type UpdateEditorConfigParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	ConfigData []byte `json:"config_data"`
}

func (q *Queries) UpdateEditorConfig(ctx context.Context, arg UpdateEditorConfigParams) (EditorConfig, error) {
	row := q.db.QueryRow(ctx, updateEditorConfig, arg.ID, arg.Name, arg.ConfigData)
	var i EditorConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
