// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: git_repo.sql

package repo

import (
	"context"
)

const addCustomFieldToGitRepo = `-- name: AddCustomFieldToGitRepo :one
UPDATE git_repo 
SET custom_fields = jsonb_set(custom_fields, $2, $3), updated_at = now()
WHERE id = $1
RETURNING id, name, core_data, custom_fields, schema_version, created_at, updated_at
`

type AddCustomFieldToGitRepoParams struct {
	ID          string      `json:"id"`
	Path        interface{} `json:"path"`
	Replacement []byte      `json:"replacement"`
}

func (q *Queries) AddCustomFieldToGitRepo(ctx context.Context, arg AddCustomFieldToGitRepoParams) (GitRepo, error) {
	row := q.db.QueryRow(ctx, addCustomFieldToGitRepo, arg.ID, arg.Path, arg.Replacement)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGitRepo = `-- name: CreateGitRepo :one
INSERT INTO git_repo (name, core_data, custom_fields, schema_version)
VALUES ($1, $2, $3, $4)
RETURNING id, name, core_data, custom_fields, schema_version, created_at, updated_at
`

type CreateGitRepoParams struct {
	Name          string `json:"name"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) CreateGitRepo(ctx context.Context, arg CreateGitRepoParams) (GitRepo, error) {
	row := q.db.QueryRow(ctx, createGitRepo,
		arg.Name,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitRepo = `-- name: DeleteGitRepo :exec
DELETE FROM git_repo
WHERE id = $1
`

func (q *Queries) DeleteGitRepo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGitRepo, id)
	return err
}

const getGitRepo = `-- name: GetGitRepo :one
SELECT id, name, core_data, custom_fields, schema_version, created_at, updated_at FROM git_repo
WHERE id = $1
`

func (q *Queries) GetGitRepo(ctx context.Context, id string) (GitRepo, error) {
	row := q.db.QueryRow(ctx, getGitRepo, id)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitRepos = `-- name: ListGitRepos :many
SELECT id, name, core_data, custom_fields, schema_version, created_at, updated_at FROM git_repo
ORDER BY created_at DESC
`

func (q *Queries) ListGitRepos(ctx context.Context) ([]GitRepo, error) {
	rows, err := q.db.Query(ctx, listGitRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitRepo{}
	for rows.Next() {
		var i GitRepo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGitReposByField = `-- name: SearchGitReposByField :many
SELECT id, name, core_data, custom_fields, schema_version, created_at, updated_at FROM git_repo
WHERE core_data @> $1 OR custom_fields @> $1
ORDER BY created_at DESC
`

func (q *Queries) SearchGitReposByField(ctx context.Context, coreData []byte) ([]GitRepo, error) {
	rows, err := q.db.Query(ctx, searchGitReposByField, coreData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitRepo{}
	for rows.Next() {
		var i GitRepo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitRepo = `-- name: UpdateGitRepo :one
UPDATE git_repo 
SET name = $2, core_data = $3, custom_fields = $4, schema_version = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdateGitRepoParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) UpdateGitRepo(ctx context.Context, arg UpdateGitRepoParams) (GitRepo, error) {
	row := q.db.QueryRow(ctx, updateGitRepo,
		arg.ID,
		arg.Name,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGitRepoField = `-- name: UpdateGitRepoField :one
UPDATE git_repo 
SET core_data = jsonb_set(core_data, $2, $3), updated_at = now()
WHERE id = $1
RETURNING id, name, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdateGitRepoFieldParams struct {
	ID          string      `json:"id"`
	Path        interface{} `json:"path"`
	Replacement []byte      `json:"replacement"`
}

func (q *Queries) UpdateGitRepoField(ctx context.Context, arg UpdateGitRepoFieldParams) (GitRepo, error) {
	row := q.db.QueryRow(ctx, updateGitRepoField, arg.ID, arg.Path, arg.Replacement)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
