// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: log_entry.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLogEntry = `-- name: CreateLogEntry :one
INSERT INTO log_entry (level, message, core_data, custom_fields, schema_version, timestamp)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, level, message, core_data, custom_fields, schema_version, timestamp, created_at, updated_at
`

type CreateLogEntryParams struct {
	Level         string           `json:"level"`
	Message       string           `json:"message"`
	CoreData      []byte           `json:"core_data"`
	CustomFields  []byte           `json:"custom_fields"`
	SchemaVersion *int32           `json:"schema_version"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
}

func (q *Queries) CreateLogEntry(ctx context.Context, arg CreateLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRow(ctx, createLogEntry,
		arg.Level,
		arg.Message,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
		arg.Timestamp,
	)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.Message,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLogEntry = `-- name: DeleteLogEntry :exec
DELETE FROM log_entry
WHERE id = $1
`

func (q *Queries) DeleteLogEntry(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLogEntry, id)
	return err
}

const getLogEntry = `-- name: GetLogEntry :one
SELECT id, level, message, core_data, custom_fields, schema_version, timestamp, created_at, updated_at FROM log_entry
WHERE id = $1
`

func (q *Queries) GetLogEntry(ctx context.Context, id string) (LogEntry, error) {
	row := q.db.QueryRow(ctx, getLogEntry, id)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.Message,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLogEntries = `-- name: ListLogEntries :many
SELECT id, level, message, core_data, custom_fields, schema_version, timestamp, created_at, updated_at FROM log_entry
ORDER BY timestamp DESC
`

func (q *Queries) ListLogEntries(ctx context.Context) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, listLogEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogEntry{}
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEntriesByLevel = `-- name: ListLogEntriesByLevel :many
SELECT id, level, message, core_data, custom_fields, schema_version, timestamp, created_at, updated_at FROM log_entry
WHERE level = $1
ORDER BY timestamp DESC
`

func (q *Queries) ListLogEntriesByLevel(ctx context.Context, level string) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, listLogEntriesByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogEntry{}
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEntriesByTimeRange = `-- name: ListLogEntriesByTimeRange :many
SELECT id, level, message, core_data, custom_fields, schema_version, timestamp, created_at, updated_at FROM log_entry
WHERE timestamp BETWEEN $1 AND $2
ORDER BY timestamp DESC
`

type ListLogEntriesByTimeRangeParams struct {
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

func (q *Queries) ListLogEntriesByTimeRange(ctx context.Context, arg ListLogEntriesByTimeRangeParams) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, listLogEntriesByTimeRange, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogEntry{}
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogEntriesByField = `-- name: SearchLogEntriesByField :many
SELECT id, level, message, core_data, custom_fields, schema_version, timestamp, created_at, updated_at FROM log_entry
WHERE core_data @> $1 OR custom_fields @> $1
ORDER BY timestamp DESC
`

func (q *Queries) SearchLogEntriesByField(ctx context.Context, coreData []byte) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, searchLogEntriesByField, coreData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogEntry{}
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLogEntry = `-- name: UpdateLogEntry :one
UPDATE log_entry 
SET level = $2, message = $3, core_data = $4, custom_fields = $5, 
    schema_version = $6, updated_at = now()
WHERE id = $1
RETURNING id, level, message, core_data, custom_fields, schema_version, timestamp, created_at, updated_at
`

type UpdateLogEntryParams struct {
	ID            string `json:"id"`
	Level         string `json:"level"`
	Message       string `json:"message"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) UpdateLogEntry(ctx context.Context, arg UpdateLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRow(ctx, updateLogEntry,
		arg.ID,
		arg.Level,
		arg.Message,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.Message,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
