// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plist_data.sql

package repo

import (
	"context"
)

const createPlistData = `-- name: CreatePlistData :one
INSERT INTO plist_data (key, core_data, custom_fields, schema_version)
VALUES ($1, $2, $3, $4)
RETURNING id, key, core_data, custom_fields, schema_version, created_at, updated_at
`

type CreatePlistDataParams struct {
	Key           string `json:"key"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) CreatePlistData(ctx context.Context, arg CreatePlistDataParams) (PlistDatum, error) {
	row := q.db.QueryRow(ctx, createPlistData,
		arg.Key,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i PlistDatum
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlistData = `-- name: DeletePlistData :exec
DELETE FROM plist_data
WHERE id = $1
`

func (q *Queries) DeletePlistData(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePlistData, id)
	return err
}

const getPlistData = `-- name: GetPlistData :one
SELECT id, key, core_data, custom_fields, schema_version, created_at, updated_at FROM plist_data
WHERE id = $1
`

func (q *Queries) GetPlistData(ctx context.Context, id string) (PlistDatum, error) {
	row := q.db.QueryRow(ctx, getPlistData, id)
	var i PlistDatum
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlistData = `-- name: ListPlistData :many
SELECT id, key, core_data, custom_fields, schema_version, created_at, updated_at FROM plist_data
ORDER BY created_at DESC
`

func (q *Queries) ListPlistData(ctx context.Context) ([]PlistDatum, error) {
	rows, err := q.db.Query(ctx, listPlistData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlistDatum{}
	for rows.Next() {
		var i PlistDatum
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlistDataByKey = `-- name: ListPlistDataByKey :many
SELECT id, key, core_data, custom_fields, schema_version, created_at, updated_at FROM plist_data
WHERE key ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) ListPlistDataByKey(ctx context.Context, dollar_1 string) ([]PlistDatum, error) {
	rows, err := q.db.Query(ctx, listPlistDataByKey, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlistDatum{}
	for rows.Next() {
		var i PlistDatum
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlistDataByField = `-- name: SearchPlistDataByField :many
SELECT id, key, core_data, custom_fields, schema_version, created_at, updated_at FROM plist_data
WHERE core_data @> $1 OR custom_fields @> $1
ORDER BY created_at DESC
`

func (q *Queries) SearchPlistDataByField(ctx context.Context, coreData []byte) ([]PlistDatum, error) {
	rows, err := q.db.Query(ctx, searchPlistDataByField, coreData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlistDatum{}
	for rows.Next() {
		var i PlistDatum
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlistData = `-- name: UpdatePlistData :one
UPDATE plist_data 
SET key = $2, core_data = $3, custom_fields = $4, 
    schema_version = $5, updated_at = now()
WHERE id = $1
RETURNING id, key, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdatePlistDataParams struct {
	ID            string `json:"id"`
	Key           string `json:"key"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) UpdatePlistData(ctx context.Context, arg UpdatePlistDataParams) (PlistDatum, error) {
	row := q.db.QueryRow(ctx, updatePlistData,
		arg.ID,
		arg.Key,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i PlistDatum
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
