// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	AddCustomFieldToDockerContainer(ctx context.Context, arg AddCustomFieldToDockerContainerParams) (DockerContainer, error)
	AddCustomFieldToGitRepo(ctx context.Context, arg AddCustomFieldToGitRepoParams) (GitRepo, error)
	CreateCacheData(ctx context.Context, arg CreateCacheDataParams) (CacheDatum, error)
	CreateDockerContainer(ctx context.Context, arg CreateDockerContainerParams) (DockerContainer, error)
	CreateEditorConfig(ctx context.Context, arg CreateEditorConfigParams) (EditorConfig, error)
	CreateGitRepo(ctx context.Context, arg CreateGitRepoParams) (GitRepo, error)
	CreateLogEntry(ctx context.Context, arg CreateLogEntryParams) (LogEntry, error)
	CreatePlistData(ctx context.Context, arg CreatePlistDataParams) (PlistDatum, error)
	CreateRegistryData(ctx context.Context, arg CreateRegistryDataParams) (RegistryDatum, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateTableSchema(ctx context.Context, arg CreateTableSchemaParams) (TableSchema, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	CreateWorkflowEdge(ctx context.Context, arg CreateWorkflowEdgeParams) (WorkflowEdge, error)
	CreateWorkflowNode(ctx context.Context, arg CreateWorkflowNodeParams) (WorkflowNode, error)
	DeactivateOldSchemas(ctx context.Context, arg DeactivateOldSchemasParams) error
	DeleteCacheData(ctx context.Context, id string) error
	DeleteDockerContainer(ctx context.Context, id string) error
	DeleteEditorConfig(ctx context.Context, id string) error
	DeleteGitRepo(ctx context.Context, id string) error
	DeleteLogEntry(ctx context.Context, id string) error
	DeletePlistData(ctx context.Context, id string) error
	DeleteRegistryData(ctx context.Context, id string) error
	DeleteSecret(ctx context.Context, id string) error
	DeleteWorkflow(ctx context.Context, id string) error
	GetCacheData(ctx context.Context, id string) (CacheDatum, error)
	GetDockerContainer(ctx context.Context, id string) (DockerContainer, error)
	GetEditorConfig(ctx context.Context, id string) (EditorConfig, error)
	GetGitRepo(ctx context.Context, id string) (GitRepo, error)
	GetLogEntry(ctx context.Context, id string) (LogEntry, error)
	GetPlistData(ctx context.Context, id string) (PlistDatum, error)
	GetRegistryData(ctx context.Context, id string) (RegistryDatum, error)
	GetSecret(ctx context.Context, id string) (Secret, error)
	GetTableSchema(ctx context.Context, tableName string) (TableSchema, error)
	GetTableSchemaByVersion(ctx context.Context, arg GetTableSchemaByVersionParams) (TableSchema, error)
	GetWorkflow(ctx context.Context, id string) (Workflow, error)
	GetWorkflowEdges(ctx context.Context, workflowID string) ([]WorkflowEdge, error)
	GetWorkflowNodes(ctx context.Context, workflowID string) ([]WorkflowNode, error)
	ListCacheData(ctx context.Context) ([]CacheDatum, error)
	ListCacheDataByTechnology(ctx context.Context, technology string) ([]CacheDatum, error)
	ListDockerContainers(ctx context.Context) ([]DockerContainer, error)
	ListEditorConfigs(ctx context.Context) ([]EditorConfig, error)
	ListGitRepos(ctx context.Context) ([]GitRepo, error)
	ListLogEntries(ctx context.Context) ([]LogEntry, error)
	ListLogEntriesByLevel(ctx context.Context, level string) ([]LogEntry, error)
	ListLogEntriesByTimeRange(ctx context.Context, arg ListLogEntriesByTimeRangeParams) ([]LogEntry, error)
	ListPlistData(ctx context.Context) ([]PlistDatum, error)
	ListPlistDataByKey(ctx context.Context, dollar_1 string) ([]PlistDatum, error)
	ListRegistryData(ctx context.Context) ([]RegistryDatum, error)
	ListRegistryDataBySubkey(ctx context.Context, dollar_1 string) ([]RegistryDatum, error)
	ListSecrets(ctx context.Context) ([]Secret, error)
	ListTableSchemas(ctx context.Context, tableName string) ([]TableSchema, error)
	ListWorkflows(ctx context.Context) ([]Workflow, error)
	RemoveFieldFromDockerContainer(ctx context.Context, arg RemoveFieldFromDockerContainerParams) (DockerContainer, error)
	SearchCacheDataByField(ctx context.Context, coreData []byte) ([]CacheDatum, error)
	SearchDockerContainersByField(ctx context.Context, coreData []byte) ([]DockerContainer, error)
	SearchGitReposByField(ctx context.Context, coreData []byte) ([]GitRepo, error)
	SearchLogEntriesByField(ctx context.Context, coreData []byte) ([]LogEntry, error)
	SearchPlistDataByField(ctx context.Context, coreData []byte) ([]PlistDatum, error)
	SearchRegistryDataByField(ctx context.Context, coreData []byte) ([]RegistryDatum, error)
	SearchSecretsByDescription(ctx context.Context, dollar_1 string) ([]Secret, error)
	SearchSecretsByField(ctx context.Context, coreData []byte) ([]Secret, error)
	UpdateCacheData(ctx context.Context, arg UpdateCacheDataParams) (CacheDatum, error)
	UpdateDockerContainer(ctx context.Context, arg UpdateDockerContainerParams) (DockerContainer, error)
	UpdateDockerContainerField(ctx context.Context, arg UpdateDockerContainerFieldParams) (DockerContainer, error)
	UpdateEditorConfig(ctx context.Context, arg UpdateEditorConfigParams) (EditorConfig, error)
	UpdateGitRepo(ctx context.Context, arg UpdateGitRepoParams) (GitRepo, error)
	UpdateGitRepoField(ctx context.Context, arg UpdateGitRepoFieldParams) (GitRepo, error)
	UpdateLogEntry(ctx context.Context, arg UpdateLogEntryParams) (LogEntry, error)
	UpdatePlistData(ctx context.Context, arg UpdatePlistDataParams) (PlistDatum, error)
	UpdateRegistryData(ctx context.Context, arg UpdateRegistryDataParams) (RegistryDatum, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
	UpdateTableSchema(ctx context.Context, arg UpdateTableSchemaParams) (TableSchema, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
