// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: registry_data.sql

package repo

import (
	"context"
)

const createRegistryData = `-- name: CreateRegistryData :one
INSERT INTO registry_data (subkey, value_name, core_data, custom_fields, schema_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subkey, value_name, core_data, custom_fields, schema_version, created_at, updated_at
`

type CreateRegistryDataParams struct {
	Subkey        string `json:"subkey"`
	ValueName     string `json:"value_name"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) CreateRegistryData(ctx context.Context, arg CreateRegistryDataParams) (RegistryDatum, error) {
	row := q.db.QueryRow(ctx, createRegistryData,
		arg.Subkey,
		arg.ValueName,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i RegistryDatum
	err := row.Scan(
		&i.ID,
		&i.Subkey,
		&i.ValueName,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRegistryData = `-- name: DeleteRegistryData :exec
DELETE FROM registry_data
WHERE id = $1
`

func (q *Queries) DeleteRegistryData(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRegistryData, id)
	return err
}

const getRegistryData = `-- name: GetRegistryData :one
SELECT id, subkey, value_name, core_data, custom_fields, schema_version, created_at, updated_at FROM registry_data
WHERE id = $1
`

func (q *Queries) GetRegistryData(ctx context.Context, id string) (RegistryDatum, error) {
	row := q.db.QueryRow(ctx, getRegistryData, id)
	var i RegistryDatum
	err := row.Scan(
		&i.ID,
		&i.Subkey,
		&i.ValueName,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistryData = `-- name: ListRegistryData :many
SELECT id, subkey, value_name, core_data, custom_fields, schema_version, created_at, updated_at FROM registry_data
ORDER BY created_at DESC
`

func (q *Queries) ListRegistryData(ctx context.Context) ([]RegistryDatum, error) {
	rows, err := q.db.Query(ctx, listRegistryData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryDatum{}
	for rows.Next() {
		var i RegistryDatum
		if err := rows.Scan(
			&i.ID,
			&i.Subkey,
			&i.ValueName,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryDataBySubkey = `-- name: ListRegistryDataBySubkey :many
SELECT id, subkey, value_name, core_data, custom_fields, schema_version, created_at, updated_at FROM registry_data
WHERE subkey ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) ListRegistryDataBySubkey(ctx context.Context, dollar_1 string) ([]RegistryDatum, error) {
	rows, err := q.db.Query(ctx, listRegistryDataBySubkey, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryDatum{}
	for rows.Next() {
		var i RegistryDatum
		if err := rows.Scan(
			&i.ID,
			&i.Subkey,
			&i.ValueName,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRegistryDataByField = `-- name: SearchRegistryDataByField :many
SELECT id, subkey, value_name, core_data, custom_fields, schema_version, created_at, updated_at FROM registry_data
WHERE core_data @> $1 OR custom_fields @> $1
ORDER BY created_at DESC
`

func (q *Queries) SearchRegistryDataByField(ctx context.Context, coreData []byte) ([]RegistryDatum, error) {
	rows, err := q.db.Query(ctx, searchRegistryDataByField, coreData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryDatum{}
	for rows.Next() {
		var i RegistryDatum
		if err := rows.Scan(
			&i.ID,
			&i.Subkey,
			&i.ValueName,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistryData = `-- name: UpdateRegistryData :one
UPDATE registry_data 
SET subkey = $2, value_name = $3, core_data = $4, custom_fields = $5, 
    schema_version = $6, updated_at = now()
WHERE id = $1
RETURNING id, subkey, value_name, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdateRegistryDataParams struct {
	ID            string `json:"id"`
	Subkey        string `json:"subkey"`
	ValueName     string `json:"value_name"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) UpdateRegistryData(ctx context.Context, arg UpdateRegistryDataParams) (RegistryDatum, error) {
	row := q.db.QueryRow(ctx, updateRegistryData,
		arg.ID,
		arg.Subkey,
		arg.ValueName,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i RegistryDatum
	err := row.Scan(
		&i.ID,
		&i.Subkey,
		&i.ValueName,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
