// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: secret.sql

package repo

import (
	"context"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secret (description, core_data, custom_fields, schema_version)
VALUES ($1, $2, $3, $4)
RETURNING id, description, core_data, custom_fields, schema_version, created_at, updated_at
`

type CreateSecretParams struct {
	Description   string `json:"description"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.Description,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secret
WHERE id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, description, core_data, custom_fields, schema_version, created_at, updated_at FROM secret
WHERE id = $1
`

func (q *Queries) GetSecret(ctx context.Context, id string) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, description, core_data, custom_fields, schema_version, created_at, updated_at FROM secret
ORDER BY created_at DESC
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSecretsByDescription = `-- name: SearchSecretsByDescription :many
SELECT id, description, core_data, custom_fields, schema_version, created_at, updated_at FROM secret
WHERE description ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) SearchSecretsByDescription(ctx context.Context, dollar_1 string) ([]Secret, error) {
	rows, err := q.db.Query(ctx, searchSecretsByDescription, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSecretsByField = `-- name: SearchSecretsByField :many
SELECT id, description, core_data, custom_fields, schema_version, created_at, updated_at FROM secret
WHERE core_data @> $1 OR custom_fields @> $1
ORDER BY created_at DESC
`

func (q *Queries) SearchSecretsByField(ctx context.Context, coreData []byte) ([]Secret, error) {
	rows, err := q.db.Query(ctx, searchSecretsByField, coreData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CoreData,
			&i.CustomFields,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secret 
SET description = $2, core_data = $3, custom_fields = $4, 
    schema_version = $5, updated_at = now()
WHERE id = $1
RETURNING id, description, core_data, custom_fields, schema_version, created_at, updated_at
`

type UpdateSecretParams struct {
	ID            string `json:"id"`
	Description   string `json:"description"`
	CoreData      []byte `json:"core_data"`
	CustomFields  []byte `json:"custom_fields"`
	SchemaVersion *int32 `json:"schema_version"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret,
		arg.ID,
		arg.Description,
		arg.CoreData,
		arg.CustomFields,
		arg.SchemaVersion,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CoreData,
		&i.CustomFields,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
