// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflow (name, version, export_date, node_count, edge_count, port_count, workflow_data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, version, export_date, node_count, edge_count, port_count, workflow_data, created_at, updated_at
`

type CreateWorkflowParams struct {
	Name         string           `json:"name"`
	Version      *string          `json:"version"`
	ExportDate   pgtype.Timestamp `json:"export_date"`
	NodeCount    *int32           `json:"node_count"`
	EdgeCount    *int32           `json:"edge_count"`
	PortCount    *int32           `json:"port_count"`
	WorkflowData []byte           `json:"workflow_data"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.Name,
		arg.Version,
		arg.ExportDate,
		arg.NodeCount,
		arg.EdgeCount,
		arg.PortCount,
		arg.WorkflowData,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.ExportDate,
		&i.NodeCount,
		&i.EdgeCount,
		&i.PortCount,
		&i.WorkflowData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowEdge = `-- name: CreateWorkflowEdge :one
INSERT INTO workflow_edge (workflow_id, from_node, to_node, label, edge_data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_id, from_node, to_node, label, edge_data, created_at
`

type CreateWorkflowEdgeParams struct {
	WorkflowID string  `json:"workflow_id"`
	FromNode   string  `json:"from_node"`
	ToNode     string  `json:"to_node"`
	Label      *string `json:"label"`
	EdgeData   []byte  `json:"edge_data"`
}

func (q *Queries) CreateWorkflowEdge(ctx context.Context, arg CreateWorkflowEdgeParams) (WorkflowEdge, error) {
	row := q.db.QueryRow(ctx, createWorkflowEdge,
		arg.WorkflowID,
		arg.FromNode,
		arg.ToNode,
		arg.Label,
		arg.EdgeData,
	)
	var i WorkflowEdge
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.FromNode,
		&i.ToNode,
		&i.Label,
		&i.EdgeData,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowNode = `-- name: CreateWorkflowNode :one
INSERT INTO workflow_node (workflow_id, node_id, label, group_type, title, x_position, y_position, node_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workflow_id, node_id, label, group_type, title, x_position, y_position, node_data, created_at
`

type CreateWorkflowNodeParams struct {
	WorkflowID string         `json:"workflow_id"`
	NodeID     string         `json:"node_id"`
	Label      *string        `json:"label"`
	GroupType  *string        `json:"group_type"`
	Title      string         `json:"title"`
	XPosition  pgtype.Numeric `json:"x_position"`
	YPosition  pgtype.Numeric `json:"y_position"`
	NodeData   []byte         `json:"node_data"`
}

func (q *Queries) CreateWorkflowNode(ctx context.Context, arg CreateWorkflowNodeParams) (WorkflowNode, error) {
	row := q.db.QueryRow(ctx, createWorkflowNode,
		arg.WorkflowID,
		arg.NodeID,
		arg.Label,
		arg.GroupType,
		arg.Title,
		arg.XPosition,
		arg.YPosition,
		arg.NodeData,
	)
	var i WorkflowNode
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.NodeID,
		&i.Label,
		&i.GroupType,
		&i.Title,
		&i.XPosition,
		&i.YPosition,
		&i.NodeData,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflow
WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, name, version, export_date, node_count, edge_count, port_count, workflow_data, created_at, updated_at FROM workflow
WHERE id = $1
`

func (q *Queries) GetWorkflow(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.ExportDate,
		&i.NodeCount,
		&i.EdgeCount,
		&i.PortCount,
		&i.WorkflowData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowEdges = `-- name: GetWorkflowEdges :many
SELECT id, workflow_id, from_node, to_node, label, edge_data, created_at FROM workflow_edge
WHERE workflow_id = $1
ORDER BY created_at
`

func (q *Queries) GetWorkflowEdges(ctx context.Context, workflowID string) ([]WorkflowEdge, error) {
	rows, err := q.db.Query(ctx, getWorkflowEdges, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowEdge{}
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.FromNode,
			&i.ToNode,
			&i.Label,
			&i.EdgeData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowNodes = `-- name: GetWorkflowNodes :many
SELECT id, workflow_id, node_id, label, group_type, title, x_position, y_position, node_data, created_at FROM workflow_node
WHERE workflow_id = $1
ORDER BY created_at
`

func (q *Queries) GetWorkflowNodes(ctx context.Context, workflowID string) ([]WorkflowNode, error) {
	rows, err := q.db.Query(ctx, getWorkflowNodes, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowNode{}
	for rows.Next() {
		var i WorkflowNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.NodeID,
			&i.Label,
			&i.GroupType,
			&i.Title,
			&i.XPosition,
			&i.YPosition,
			&i.NodeData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, version, export_date, node_count, edge_count, port_count, workflow_data, created_at, updated_at FROM workflow
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.ExportDate,
			&i.NodeCount,
			&i.EdgeCount,
			&i.PortCount,
			&i.WorkflowData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflow 
SET name = $2, version = $3, export_date = $4, node_count = $5, edge_count = $6, 
    port_count = $7, workflow_data = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, version, export_date, node_count, edge_count, port_count, workflow_data, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Version      *string          `json:"version"`
	ExportDate   pgtype.Timestamp `json:"export_date"`
	NodeCount    *int32           `json:"node_count"`
	EdgeCount    *int32           `json:"edge_count"`
	PortCount    *int32           `json:"port_count"`
	WorkflowData []byte           `json:"workflow_data"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.ExportDate,
		arg.NodeCount,
		arg.EdgeCount,
		arg.PortCount,
		arg.WorkflowData,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.ExportDate,
		&i.NodeCount,
		&i.EdgeCount,
		&i.PortCount,
		&i.WorkflowData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
